name: Continuous build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: ./gradlew assemble
      - uses: actions/upload-artifact@v2.0.0
        with:
          name: kotlin-math
          path: ./build/libs/kotlin-math-*.jar
